apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator-kafka-broker-delegation
  labels:
    app: strimzi
subjects:
- kind: ServiceAccount
  name: strimzi-cluster-operator
roleRef:
  kind: Role
  name: strimzi-kafka-broker
  apiGroup: rbac.authorization.k8s.io
